### ISSUE TITLE
perf_to_profile fails with large (18gb) perf data

### ISSUE THREAD

**Issue by JustinStitt** [google/perf_data_converter#123]
I generated perf data with a clang linux build
`$ perf record -e cycles:pp --output=arm64_clang_built_def_config.data --call-graph lbr -- make LLVM=1 -j72 ARCH=arm64`

Which had a (quite large) size of: 
```
$ du -h arm64_clang_built_def_config.data 
18G     arm64_clang_built_def_config.data
```

Invoking the `perf_to_profile` tool yields this output:
```
$ perf_to_profile -i arm64_clang_built_def_config.data -o profile_arm64_clang_built_defconfig
[ERROR:src/quipper/perf_reader.cc:197] perf_file_section.size 19150652112 cannot exceed remaining perf data input size 1970824676 at offset 824
[ERROR:src/quipper/perf_reader.cc:813] Error reading header file section info.
[ERROR:src/perf_data_converter.cc:749] Could not read input perf.data
[FATAL:src/perf_to_profile.cc:33] Expected profile vector to have one element.
```

For reference, that first number `19150652112` is ~19gb and the second `1970824676` is ~1.9gb.

#### Steps to reproduce:
run the `perf_to_profile` tool on a large perf.data. (I am not exactly sure how large of a file is required to reproduce, but I know for sure >=18gb does the trick)

edit: as per my comment (and fixes) below, the critical size is ~2.14gb.

**Comment by JustinStitt** [comment]
I've located the problem (*and proposed a fix*):

In `perf_to_profile_lib.cc` there exists this invocation: 
```c++
return perftools::RawPerfDataToProfiles(data.data(), data.length()/* data.length() is a size_t */, {},          
                                            sample_labels, options);
```
The type of `data.length()` or its alias `data.size()` is `size_t`. The problem lies within the `perf_data_converter.cc` `RawPerfDataToProfiles()` function which expects an integer for its `raw_size` parameter. This causes integer narrowing/truncation in which no data can be read past `INT_MAX (2147483647)` or `~2.14gb`. 

See the changes below:

```diff
diff --git a/src/perf_data_converter.cc b/src/perf_data_converter.cc               
index 8775bd0..2095e82 100644                                                      
--- a/src/perf_data_converter.cc                                                   
+++ b/src/perf_data_converter.cc                                                   
@@ -741,7 +741,7 @@ ProcessProfiles PerfDataProtoToProfiles(                       
 }                                                                                 
                                                                                   
 ProcessProfiles RawPerfDataToProfiles(                                            
-    const void* raw, const uint64_t raw_size,                                     
+    const void* raw, const int raw_size,                                          
     const std::map<string, string>& build_ids, const uint32 sample_labels,        
     const uint32 options, const std::map<Tid, string>& thread_types) {            
   quipper::PerfReader reader;                                                     
diff --git a/src/perf_data_converter.h b/src/perf_data_converter.h                 
index d94d53e..8b12598 100644                                                      
--- a/src/perf_data_converter.h                                                    
+++ b/src/perf_data_converter.h                                                    
@@ -130,7 +130,7 @@ using ProcessProfiles = std::vector<std::unique_ptr<ProcessProfile>>;
 //                                                                                
 // Returns a vector of process profiles, empty if any error occurs.               
 extern ProcessProfiles RawPerfDataToProfiles(                                     
-    const void* raw, uint64_t raw_size,                                           
+    const void* raw, int raw_size,                                                
     const std::map<std::string, std::string>& build_ids,                          
     uint32 sample_labels = kNoLabels, uint32 options = kGroupByPids,              
     const std::map<uint32, std::string>& thread_types = {}); 
```

I opted for `uint64_t` as it is the widest integer type and is equivalent to size_t on 64-bit systems. I also identified instances elsewhere in the code base in which various `size` metrics were of type `u64` or `uint64_t` (aliases). It makes sense to maintain some sense of consistency.

It should be noted that the current max protobuf size is 2gb which would render this change irrelevant. If the size of protobuf were to be increased then this change would become somewhat necessary.

**Comment by shantuo** [comment]
> It should be noted that the current max protobuf size is [2gb](https://b.corp.google.com/issues/217463141). Currently, perf data is compressed (~80%) when it arrives in its final protobuf state which means this change is still worthwhile. The bottleneck is now the allowed max size of protobufs themselves. 

You're correct, this might not fix your problem if the data is way larger than the protobuf maximum. I'll submit a fix.

**Comment by shantuo** [comment]
Merged https://github.com/google/perf_data_converter/pull/124
