### ISSUE TITLE
Cannot extract function name from perf.data

### ISSUE THREAD

**Issue by yiwangethan** [google/perf_data_converter#155]
Hello! We obtain the "perf.data" file by using "perf record -g -a ./my_execution", but it seems that the "perf.data" database does not include mapping information such as function names. After using "perf_to_profile" to convert the "perf.data" file to protobuf file, we still cannot extract function name information from it. Is it possible that our command is incorrect or lacks certain flags? Thanks for your time in advance.

**Comment by aalexand** [comment]
Symbolization is not a part of the perf.data file, it's done by the analysis tool - e.g. during `perf report` or `pprof` invocation.
