### ISSUE TITLE
build failed with bazel 4.0, Arch Linux

### ISSUE THREAD

**Issue by blessingsi** [google/perf_data_converter#94]
I tried to build with bazel 4.0.0, and got an error:
```
 in proto_lang_toolchain rule @com_google_protobuf//:cc_toolchain: '@com_google_protobuf//:cc_toolchain' does not have mandatory provider 'ProtoInfo'.
```

system, archlinux:
```
Linux 5.10.13-arch1-2 #1 SMP PREEMPT Sat, 06 Feb 2021 11:07:29 +0000 x86_64 GNU/Linux
```
bazel version:
```
Build label: 4.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 21 14:04:24 2021 (1611237864)
Build timestamp: 1611237864
Build timestamp as int: 1611237864
```
I found bazelbuild/bazel#12887, and try to upgrade protobuf to v13.0, but there are some other dependency issues.

**Comment by ZachMarcus** [comment]
I've addressed this issue internally and will update this in the next day or two.

**Comment by blessingsi** [comment]
> I've addressed this issue internally and will update with the fix in the next day or two.

Thank you so much

**Comment by blessingsi** [comment]
solved. Thanks
