### ISSUE TITLE
Build failing "fips.c: No such file or directory" since 15.03.2021 (boringssl)

### ISSUE THREAD

**Issue by pbetkier** [google/perf_data_converter#96]
Project build fails for me since yesterday (15.03.2021), it worked fine earlier. The problem seems to lie in boringssl dependency, [this change](https://boringssl-review.googlesource.com/c/boringssl/+/46124) in particular.

```bash
$ bazel build src:perf_to_profile
(...)
ERROR: /root/.cache/bazel/_bazel_root/9a84914462919c338e94f245491500b7/external/boringssl/BUILD:151:11: Compiling src/crypto/fipsmodule/bcm.c failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -MD -MF ... (remaining 34 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -MD -MF ... (remaining 34 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/boringssl/src/crypto/fipsmodule/bcm.c:82:10: fatal error: fips.c: No such file or directory
 #include "fips.c"
          ^~~~~~~~
compilation terminated.
Target //src:perf_to_profile failed to build
(...)
```

Build this Dockerfile to reproduce:

```Dockerfile
FROM ubuntu:18.04

RUN apt update && apt install -y npm g++ git libelf-dev libcap-dev
RUN npm install -g @bazel/bazelisk

RUN git clone https://github.com/google/perf_data_converter.git /usr/src/perf_data_converter
WORKDIR /usr/src/perf_data_converter

# uncomment to make the build succeed
# RUN sed -i 's/\/google\/boringssl/\/pbetkier\/boringssl/' WORKSPACE

RUN bazel build src:perf_to_profile
```

Note the commented out `sed`. After uncommenting the build does pass. It replaces the official boringssl dependency with my fork that moves history before the boringssl change linked in the beginning.

I'm not sure if this is the right place to file this problem, or should I rather file it in the boringssl project. My knowledge of the cpp ecosystem is also rather limited. I hope you can direct me to the right place :)

**Comment by aalexand** [comment]
I think this should be reported to boringssl, there is little we can do about this in this repo.

**Comment by pbetkier** [comment]
FYI I reported it [here](https://bugs.chromium.org/p/boringssl/issues/detail?id=401).

**Comment by pbetkier** [comment]
It got fixed, build passes now.
